"""user table

Revision ID: 83454ef2ccbc
Revises: 
Create Date: 2019-05-08 16:41:55.652041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83454ef2ccbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue')
    op.drop_index('rating_band_fk_id', table_name='rating')
    op.drop_index('rating_user_fk_id', table_name='rating')
    op.drop_index('rating_venue_fk_id', table_name='rating')
    op.drop_table('rating')
    op.drop_index('friend_friendee_id', table_name='friend')
    op.drop_index('friend_friender_id', table_name='friend')
    op.drop_table('friend')
    op.drop_index('user_email', table_name='user')
    op.drop_index('user_username', table_name='user')
    op.drop_table('user')
    op.drop_table('band')
    op.drop_index('event_band_fk_id', table_name='event')
    op.drop_index('event_venue_fk_id', table_name='event')
    op.drop_table('event')
    op.drop_index('favorite_band_fk_id', table_name='favorite')
    op.drop_index('favorite_event_fk_id', table_name='favorite')
    op.drop_index('favorite_user_fk_id', table_name='favorite')
    op.drop_index('favorite_venue_fk_id', table_name='favorite')
    op.drop_table('favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_fk_id', sa.INTEGER(), nullable=False),
    sa.Column('band_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('venue_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('event_fk_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['band_fk_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['event_fk_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_fk_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['venue_fk_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('favorite_venue_fk_id', 'favorite', ['venue_fk_id'], unique=False)
    op.create_index('favorite_user_fk_id', 'favorite', ['user_fk_id'], unique=False)
    op.create_index('favorite_event_fk_id', 'favorite', ['event_fk_id'], unique=False)
    op.create_index('favorite_band_fk_id', 'favorite', ['band_fk_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('band_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('venue_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['band_fk_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['venue_fk_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('event_venue_fk_id', 'event', ['venue_fk_id'], unique=False)
    op.create_index('event_band_fk_id', 'event', ['band_fk_id'], unique=False)
    op.create_table('band',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('about', sa.VARCHAR(length=255), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=255), nullable=True),
    sa.Column('themes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('img', sa.BLOB(), nullable=False),
    sa.Column('skid', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('avatar', sa.BLOB(), nullable=False),
    sa.Column('user_level', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_username', 'user', ['username'], unique=1)
    op.create_index('user_email', 'user', ['email'], unique=1)
    op.create_table('friend',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('friender_id', sa.INTEGER(), nullable=False),
    sa.Column('friendee_id', sa.INTEGER(), nullable=True),
    sa.Column('accepted', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friendee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('friend_friender_id', 'friend', ['friender_id'], unique=False)
    op.create_index('friend_friendee_id', 'friend', ['friendee_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_fk_id', sa.INTEGER(), nullable=False),
    sa.Column('venue_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('band_fk_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('rating_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.VARCHAR(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['band_fk_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_fk_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['venue_fk_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rating_venue_fk_id', 'rating', ['venue_fk_id'], unique=False)
    op.create_index('rating_user_fk_id', 'rating', ['user_fk_id'], unique=False)
    op.create_index('rating_band_fk_id', 'rating', ['band_fk_id'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('img', sa.BLOB(), nullable=False),
    sa.Column('about', sa.VARCHAR(length=255), nullable=False),
    sa.Column('skid', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
